name: Python application
on:
  push:
  schedule:
    - cron: '0 21 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查分支
        uses: actions/checkout@v3

      - name: Legal Compliance Check
        run: |
          echo "▄▄▄▄▄▄▄ LEGAL NOTICE ▄▄▄▄▄▄▄"
          echo "此Action将运行autoUrl.py生成tv/内容"
          echo "您确认："
          echo "1. 不存储非法内容"
          echo "2. 接受UNLICENSE协议"
          echo "3. 生成文件仅用于技术研究示例"
          sleep 10 # 法律声明展示时间

      - name: 安装 Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.4

      - name: 安装模块
        run: |
          pip install requests
          pip install urllib3
          pip install pycryptodome
      - name: 生成json文件
        run: |
          export TZ='Asia/Shanghai'
          python autoUrl.py
      - name: 暂存提交
        run: |
          git config --global user.name 'hl128k'
          git config --global user.email 'hl128k@qq.com'
          export TZ='Asia/Shanghai'
          git add .
          git commit -m "update" -a
      - name: 推送
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
